# =========================
# AUTOSTART
# =========================
exec_once=awww-daemon
exec_once=wayle shell
exec_once=swayidle
exec_once=clipse -listen
exec_once=/usr/lib/hyprpolkitagent/hyprpolkitagent
