# =========================
# AUTOSTART
# =========================
exec-once=awww-daemon
exec-once=wayle shell
exec-once=swayidle
exec-once=clipse -listen
exec-once=/usr/lib/hyprpolkitagent/hyprpolkitagent
