# Background color of the root window
rootcolor=0x0A0A0Aff

# Inactive window border
bordercolor=0x242424ff

# Drop shadow when dragging windows
dropcolor=0x00000055

# Split window border color in manual dwindle layout
splitcolor=0x666666FF

# Active window border
focuscolor=0xD4D4D4FF

# Urgent window border (alerts)
urgentcolor=0xFFFFFFff
