env=LANG,en_IN.UTF-8
cursor_size=24
cursor_theme=Oxygen 18 White

auto_reload_config=1

#terminal="foot"
# =========================
# Tags
# =========================

tag_rule=id:8,monitor_name:HDMI-A-1,layout_name:vertical_scroller

focused_opacity=1.0
#unfocused_opacity=0.4     #if want to lower opacity of unfocused window
unfocused_opacity=1.0     #if want to keep unfocused window's opacity 100

idle_inhibit_ignore_visible=0
idle_inhibit_when_fullscreen=0
# =========================
# INPUT
# =========================
xkb_rules_layout=us
sloppy_focus=1
mouse_accel_speed=-0.5
mouse_accel_profile=2
trackpad_natural_scrolling=1
drag_lock=1

# =========================
# LOOKS
# =========================

source=~/.config/mango/looks.conf
source=~/.config/mango/color.conf

# =========================
# AUTOSTART
# =========================
source=~/.config/mango/autostart.conf

# =========================
# WINDOW RULES
# =========================
source=~/.config/mango/windowrules.conf

# =========================
# KEYBINDS
# =========================
source=~/.config/mango/keybinds.conf

source=~/.config/mango/monitors.conf
