# =========================
# KEYBINDS
# =========================

key_mode=common
bind=SUPER,BackSpace,reload_config

# Apps
bind=SUPER,Q,spawn,foot
bind=SUPER,E,spawn,thunar
bind=SUPER+CTRL,E,spawn,foot -e elio
#bind=SUPER,B,spawn,firefox
bind=SUPER,B,spawn,zen-browser
bind=SUPER,L,spawn,localsend
#bind=CTRL,i,spawn,thunar, mmsg dispatch togglefloating && mmsg dispatch resizewin,1000,700 && mmsg dispatch centerwin

#Rofi
bind=SUPER,space,spawn,rofi -show drun

# Window controls
bind=ALT,code:49,killclient,
bind=SUPER,F,togglefullscreen,
bind=SUPER,T,spawn_shell, mmsg dispatch togglefloating && mmsg dispatch resizewin,1000,700 && mmsg dispatch centerwin
mousebind=SUPER,btn_extra,toggleoverview,
mousebind = super,btn_forward,toggleoverview

#scripts
bind=SUPER,n,spawn_shell,foot --title="Floating-Layout" -e ~/.config/mango/layout-switcher.sh
bind=SUPER,w,spawn_shell,foot --title="Floating-Wallpaper" -e ~/superior-mango-dotfiles/scripts/wallpaper.sh
bind=SUPER,p,spawn_shell,foot --title="Floating-Monitor" -e ~/superior-mango-dotfiles/scripts/monitor.sh
bind=SUPER+SHIFT,e,spawn_shell,foot --title="Floating-Powermenu" -e ~/superior-mango-dotfiles/scripts/powermenu.sh
bind=SUPER,V,spawn_shell,foot --title="Floating-Clipboard" --class clipse -e clipse

# Move focus (arrows)
bind=CTRL+ALT,h,focusdir,left
bind=CTRL+ALT,l,focusdir,right
bind=CTRL+ALT,k,focusdir,up
bind=CTRL+ALT,j,focusdir,down

# Move windows
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down

# Mouse move/resize windows
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# gaps
bind=ALT+SHIFT,X,incgaps,+10
bind=ALT+SHIFT,Z,incgaps,-10
bind=ALT+SHIFT,R,togglegaps

# Workspaces (tags)
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
#bind=SUPER,0,view,10

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9
#bind=SUPER+SHIFT,0,tag,10

bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev
bind=SUPER+SHIFT,period,exchange_client,right
bind=SUPER+SHIFT,comma,exchange_client,left

# Screenshot
bind=None,Print,spawn_shell,grim -g "$(slurp)" - | satty --filename -

# Volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# Brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +2%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 2%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 0%
