# =========================
# GENERAL (gaps / borders)
# =========================
gap_inner_horizontal=4
gap_inner_vertical=4
gap_outer_horizontal=5
gap_outer_vertical=6
border_px=1.5
no_border_when_single=1
smart_gaps=1

# =========================
# DECORATION
# =========================
#border_radius=9        # '#' to disable rounded corner

blur=1
blur_layer=1
blur_optimized=0
blur_params_radius=10
blur_params_num_passes=3
blur_params_contrast=1.1

shadows=0

# =========================
# ANIMATIONS
# =========================
animations=1
layer_animations=1

animation_type_open=zoom
animation_type_close=zoom

animation_curve_open=0.46,1.0,0.29,0.99
animation_curve_move=0.46,1.0,0.29,0.99
animation_curve_tag=0.46,1.0,0.29,0.99
animation_curve_close=0.46,1.0,0.29,0.99
animation_curve_focus=0.46,1.0,0.29,0.99
animation_curve_opacity_fade_in=0.46,1.0,0.29,0.99
animation_curve_opacity_fade_out=0.5,0.5,0.5,0.5

animation_duration_move=500
animation_duration_open=400
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=100
