# =========================
# WINDOW RULES
# =========================
window_rule=focused_opacity:0.8,unfocused_opacity:0.8,app_id:thunar

window_rule=is_floating:1,width:1100,height:700,app_id:^(com.gabm.satty)$

window_rule=is_floating:1,width:800,height:500,app_id:org.pulseaudio.pavucontrol

window_rule=is_floating:1,width:800,height:500,app_id:blueman-manager

window_rule=is_floating:1,width:1000,height:700,app_id:^(vlc)$,focused_opacity:1,unfocused_opacity:1

#TO make kitty float
#windowrule=is_floating:1,width:1000,height:700,app_id:^(kitty)$

window_rule=is_floating:1,width:1000,height:700,app_id:^(mpv)$,focused_opacity:1,unfocused_opacity:1

window_rule=is_floating:1,width:1000,height:700,app_id:^(org.kde.gwenview)$,focused_opacity:1,unfocused_opacity:1

window_rule=title:Floating-Layout,width:400,height:370,is_floating:1

window_rule=title:Floating-Wallpaper,width:700,height:500,is_floating:1

window_rule=title:Floating-Launcher,width:700,height:500,is_floating:1

window_rule=title:Floating-Clipboard,width:700,height:500,is_floating:1

window_rule=title:Floating-Monitor,width:300,height:200,is_floating:1

window_rule=title:Floating-Powermenu,width:300,height:250,is_floating:1

window_rule=tags:8,app_id:discord
window_rule=tags:8,app_id:Spotify
window_rule=tags:8,app_id:app.fluxer.Fluxer
window_rule=tags:9,app_id:com.obsproject.Studio

layer_rule=no_blur:1,layer_name:selection

