# =========================
# WINDOW RULES
# =========================
windowrule=focused_opacity:0.8,unfocused_opacity:0.8,appid:thunar

windowrule=isfloating:1,width:1100,height:700,appid:^(com.gabm.satty)$

windowrule=isfloating:1,width:800,height:500,appid:org.pulseaudio.pavucontrol

windowrule=isfloating:1,width:800,height:500,appid:blueman-manager

windowrule=isfloating:1,width:1000,height:700,appid:^(vlc)$,focused_opacity:1,unfocused_opacity:1

#TO make kitty float
#windowrule=isfloating:1,width:1000,height:700,appid:^(kitty)$

windowrule=isfloating:1,width:1000,height:700,appid:^(mpv)$,focused_opacity:1,unfocused_opacity:1

windowrule=isfloating:1,width:1000,height:700,appid:^(org.kde.gwenview)$,focused_opacity:1,unfocused_opacity:1

windowrule=title:Floating-Layout,width:400,height:370,isfloating:1

windowrule=title:Floating-Wallpaper,width:700,height:500,isfloating:1

windowrule=title:Floating-Launcher,width:700,height:500,isfloating:1

windowrule=title:Floating-Clipboard,width:700,height:500,isfloating:1

windowrule=title:Floating-Monitor,width:300,height:200,isfloating:1

windowrule=title:Floating-Powermenu,width:300,height:250,isfloating:1

windowrule=tags:8,appid:discord
windowrule=tags:8,appid:Spotify
windowrule=tags:8,appid:app.fluxer.Fluxer
windowrule=tags:9,appid:com.obsproject.Studio

layerrule=noblur:1,layer_name:selection

