# ── FONT ────────────────────────────────────────
font_family      Hurmit Nerd Font
font_size        11.0

# ── TRANSPARENCY & BLUR ─────────────────────────
background_opacity 0.72
background_blur    11

#---- Themes------
include /home/venom/.cache/wal/colors-kitty.conf

cursor_trail 11
cursor_trail_decay 0.1 0.4

shell /usr/bin/fish
